### DISCUSSION TITLE
Could I do something about missing atomic mode-setting?

### DISCUSSION THREAD

**Discussion by Mannshoch** [LizardByte/community#491] [Sunshine]
Could I do something about missing atomic mode-setting?

```
2024:08:02:23:35:24]: Info: Screencasting with KMS
[2024:08:02:23:35:24]: Info: /dev/dri/card0 -> radeon
[2024:08:02:23:35:24]: Warning: GPU driver doesn't support atomic mode-setting: /dev/dri/card0
[2024:08:02:23:35:24]: Warning: Cursor capture may fail without atomic mode-setting support!
```

```
Graphics:
  Device-1: AMD Turks PRO [Radeon HD 6570/7570/8550 / R5 230] driver: radeon
    v: kernel
  Device-2: Logitech Webcam Pro 9000 driver: snd-usb-audio,uvcvideo
    type: USB
  Display: wayland server: X.Org v: 23.2.6 with: Xwayland v: 23.2.6
    compositor: gnome-shell v: 46.0 driver: X: loaded: radeon
    unloaded: fbdev,modesetting,vesa dri: r600 gpu: radeon
    resolution: 2560x1440~60Hz
  API: EGL v: 1.5 drivers: kms_swrast,r600,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.5 vendor: mesa v: 24.0.9-0ubuntu0.1 renderer: AMD TURKS
    (DRM 2.50.0 / 6.8.0-39-generic LLVM 17.0.6)
  API: Vulkan v: 1.3.275 drivers: N/A surfaces: xcb,xlib,wayland

```

[a comment by an automated account is not shown]
